// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"layout-item/configs"
	"layout-item/internal/vip/repository"
	"layout-item/pkg/db"
)

// Injectors from wire.go:

func InitUserServer(cfg configs.MYSQL) *VipServer {
	dbConnMap := db.NewDBConnMap(cfg)
	vipDbStore := repository.NewVipDbStore(dbConnMap)
	vipService := NewVipService(vipDbStore)
	vipServer := NewVipServer(vipService)
	return vipServer
}
